# macOS Monterey inspired Kitty Theme (Purples, Pinks & Blues)

background            #120c1f
foreground            #e2daf1
cursor                #e2daf1
selection_background  #47225d
selection_foreground  #120c1f

# Black (Deep Purple-Black)
color0                #120c1f
color8                #6c5584

# Red (Vibrant Magenta / Hot Pink)
color1                #d02d76
color9                #f36ca3

# Green -> Replaced with Vibrant Ice Blues / Teals
color2                #2ab5d3
color10               #7be1f7

# Yellow -> Replaced with Soft Pastel Pink / Peach
color3                #f397be
color11               #fbcbe0

# Blue (Electric Violet / Deep Blue)
color4                #4e6aff
color12               #8e9eff

# Magenta (Royal Purple)
color5                #8b33b7
color13               #ca7eff

# Cyan (Soft Lilac / Lavender Sky)
color6                #9b87db
color14               #d2c7fc

# White (Warm Lavender-White)
color7                #e2daf1
color15               #fcf9ff